### ISSUE TITLE
Produce template-safe markup

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#115]
Over at the OWASP Java HTML Sanitizer project, we're currently collecting features of template expressions for client- (and server-)side frameworks.

What we want to do for DOMPurify is to provide an additional flag that allows to produce HTML that is safe for templating engines - meaning it cannot contain any expressions after sanitization. This includes handlebars, ERB, more exotic formats (like Kendo UIs `# alert(1) #`) as well as custom data attributes.

**Examples:**
https://github.com/OWASP/java-html-sanitizer/blob/master/docs/client-side-templates.md

Is there any more formats and relevant frameworks that need to be covered?

**Flag suggestions:**
`SAFE_FOR_TEMPLATING`

**Tasks:**
- [ ] Enumerate container formats
- [ ] Enumerate dangerous attributes
- [x] Implement flag
- [x] Filter element content and attributes

**Comment by cure53** [comment]
We do have two regular expressions for template detection and removal:
https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L550

We also have a new and working config flag:
https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L256

Not sure if we should blacklist `class` because AngularJS once the template flag is set. I would think, exotic delimiters like KendoUI allows them should not be supported.

What we do need though is a custom regex for developer-controlled regex. 
Or should that better be done by a hook?

**Comment by cure53** [comment]
This should be okay for now. Waiting to get usage reports and feature requests.

**Comment by mostprovikki** [comment]
Any specific reason why the regular expressions for template detection are constructed in this way?

`/\{\{[\s\S]*|[\s\S]*\}\}/gm/` and `/<%[\s\S]*|[\s\S]*%>/gm`

They don't exactly match only the templates and they don't match the entire string also. In some cases, they match innocuous strings like `Hello World}}`

Eg.
In the string `foo {{bar}} baz`, it matches only`foo {{bar}}`

I propose the following regular expressions for template detection.
`/\{\{[\s\S]+?\}\}/gm`
`/<%[\s\S]+?%>/gm`

This exactly matches only the template expressions as far as I have tested.

**Comment by cure53** [comment]
We had some bypasses in the past, using template expressions stretched over multiple HTML nodes.

I am not against renovating the regex a bit though, did you check if the tests are still green with your proposal? https://github.com/cure53/DOMPurify/blob/master/test/test-suite.js#L66

**Comment by mostprovikki** [comment]
I apologise for the delayed response.

If there are bypasses using template expressions stretched over multiple HTML nodes, then it is better to keep the existing regex itself.

The regex I proposed did not catch the template expressions stretched over multiple nodes but I thought they were harmless till now. Thanks for the quick reply. 

BTW, DOMPurify is an awesome product! Keep up the good work!
